#!/bin/bash

################ config and compile dpdk  ################ 
# cd dpdk
# make config T=x86_64-native-linuxapp-gcc
# make install T=x86_64-native-linuxapp-gcc
########################################################

################ config and compile ovs ################ 
# cd ovs
# ./boot.sh
# ./configure --localstatedir=/var --with-dpdk=/root/workplane/dpdk/x86_64-native-linuxapp-gcc
# make
# make install
########################################################

DPDK_DIR=/root/workplane/dpdk-2.1.0
DPDK_BUILD=/root/workplane/dpdk-2.1.0/x86_64-native-linuxapp-gcc
export DPDK_DIR DPDK_BUILD

## set hugepage number, use boot cmdline or procfs 
echo 2048 > /proc/sys/vm/nr_hugepages

## insert the kernel modules
modprobe uio
insmod $DPDK_BUILD/kmod/igb_uio.ko
insmod $DPDK_BUILD/kmod/rte_kni.ko
insmod $DPDK_DIR/lib/librte_vhost/eventfd_link/eventfd_link.ko

# unbind the dpdk interface
$DPDK_DIR/tools/dpdk_nic_bind.py --bind=igb_uio eth1
$DPDK_DIR/tools/dpdk_nic_bind.py --bind=igb_uio eth2
# $DPDK_DIR/tools/dpdk_nic_bind.py --bind=igb_uio eth3
# $DPDK_DIR/tools/dpdk_nic_bind.py --bind=igb_uio eth4
# $DPDK_DIR/tools/dpdk_nic_bind.py --bind=igb_uio eth5

mkdir -p /var/run/openvswitch
rm -rf /usr/local/etc/openvswitch/confi.db

## Just init once 
/usr/local/bin/ovsdb-tool create /usr/local/etc/openvswitch/conf.db /usr/local/share/openvswitch/vswitch.ovsschema

/usr/local/sbin/ovsdb-server --remote=punix:/var/run/openvswitch/db.sock \
		--remote=db:Open_vSwitch,Open_vSwitch,manager_options \
		--log-file --pidfile --detach

## Just init once 
/usr/local/bin/ovs-vsctl --no-wait init

/usr/local/sbin/ovs-vswitchd --dpdk -c 0xe -n 4 --socket-mem 2048 -- unix:/var/run/openvswitch/db.sock \
		--log-file --pidfile --detach

##############################################################################
## Add brige 
/usr/local/bin/ovs-vsctl add-br ovsbr0 -- set bridge ovsbr0 datapath_type=netdev

## Add dpdk port
/usr/local/bin/ovs-vsctl add-port ovsbr0 dpdk0 -- set Interface dpdk0 type=dpdk
/usr/local/bin/ovs-vsctl add-port ovsbr0 dpdk1 -- set Interface dpdk1 type=dpdk
# /usr/local/bin/ovs-vsctl add-port ovsbr0 dpdk2 -- set Interface dpdk2 type=dpdk
# /usr/local/bin/ovs-vsctl add-port ovsbr0 dpdk3 -- set Interface dpdk3 type=dpdk

## Add vhost-user port 
/usr/local/bin/ovs-vsctl add-port ovsbr0 vhost-user-0 -- set Interface vhost-user-0 type=dpdkvhostuser
/usr/local/bin/ovs-vsctl add-port ovsbr0 vhost-user-1 -- set Interface vhost-user-1 type=dpdkvhostuser
###############################################################################
